spring:
  application:
    name: spring-boot-actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

  info:
    build:
      enabled: true
    env:
      enabled: true
    git:
      enabled: true
      mode: full

